unique_ids:
  assets:
    standard-page.html: YDDNTYSTZCXN3KCKCDMUFZRXTOPNJNTZ
    theme.css: WWCKGK5QESLUK44LU7WS5UB6DXQNRJM3
  forms:
    Form1: ZF4DVHSHLXRVVNNYQ774QRDCIZY6AOWS
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1776726208073308262626564.8508'
