unique_ids:
  assets:
    standard-page.html: YDDNTYSTZCXN3KCKCDMUFZRXTOPNJNTZ
    theme.css: WWCKGK5QESLUK44LU7WS5UB6DXQNRJM3
  forms:
    Form1: ZF4DVHSHLXRVVNNYQ774QRDCIZY6AOWS
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1776726208073308262626564.8508'
    api_endpoints: D55QJSDB6YJS4E4YAS7LHOVGYHP6KU3U
    classifier: NBYAK45Q7MZOGKDWPW7MND3H2YZFEQS2
    generation: JT3QHN6O6QMJL75MOQMUAVOWZEXOJWPJ
    m2py: CGRWLDAH2XFDIFM6STGYHDR5AAHYOUL2
    m2py_shim: KQXZAXSUIRAV7TGXSZQHR6IMWRZ4H4VP
    prompts: GJ4O5JIQRKMNYTM3ZMW5D7I6WYCIC2QY
    retrieval: CWQCCSM6YI5NV7GUY5BNDEFNZEN737IW
    utils: FPOUFBY6OCTF5J4SL4NR3X477FLSIK7G
    validation: T2CLWEJYCE7IEE5SVM3JEQFSOPZ4WVQZ
